name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Changelog
        id: extract-changelog
        uses: sean0x42/markdown-extract@v2
        with:
          file: CHANGELOG.md
          pattern: ${{  github.ref_name }}
          no-print-matched-heading: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.extract-changelog.outputs.markdown }}
          generate_release_notes: true
